---
- name: Push Changes to Gitea Repositories
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Include repository list
      ansible.legacy.include_vars:
        file: repositories.yaml

    - name: Push changes to repositories
      ansible.builtin.command: git push {{ item.remote_name }} {{ item.branch }}
      args:
        chdir: "{{ item.path }}"
      loop: "{{ repositories_to_push }}"
      loop_control:
        loop_var: item
