---
- name: Ensure Docker is installed
  ansible.builtin.shell:
    cmd: "curl https://get.docker.com | bash -"

- name: Ensure used 'miles' exists
  ansible.builtin.user:
    name: miles
    comment: Miles
    groups: docker
    append: true
