---
- name: New Linux server install
  hosts: mainpi
  tasks:
    # Install APT packages
    - import_tasks: tasks/apt-packages.yml

    # Ensure docker is installed
    - import_tasks: tasks/install-docker.yml
