---
- name: New Linux server install
  hosts: mainpi
  tasks:
    # Install APT packages
    - ansible.legacy.import_tasks: tasks/apt-packages.yml

    # Ensure docker is installed
    - ansible.legacy.import_tasks: tasks/install-docker.yml
