---
name: YAML Lint

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Ansible Lint
        uses: ansible/ansible-lint-action@v4
        with:
          args: .
