name: YAML Lint

on:
  push:
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: YAML lint
        uses: sdesbure/yamllint-action@v1
        with:
          args: .

